public class Kasztolas {

    public static void main(String[] args) {
        byte bit = 50;
        short keves = 150;
        int sok = 500000;
        int okt = 050;
        int hex = 0x102;
        long hosszu = 50000000000L;
        float lebegos = 5.0f;
        double dupla = 28.5d;
        float lebegosexpo = 5e0f;
        double duplaexpo = 28E5d;
        //System.out.println(bit, keves, sok, okt, hex, hosszu, lebegos, dupla, lebegosexpo, duplaexpo);
        double MyDouble = 15.4d;
        float myFloat = (float) MyDouble;
        long myLong = (long) MyDouble;
        int myInt = (int) MyDouble;
        char myChar = (char) MyDouble;
        short myShort = (short) MyDouble;
        byte myByte = (byte) MyDouble;
        float MyFloat1 = 15.4f;
        double myDouble1 = (double) MyFloat1;
        long myLong1 = (long) MyFloat1;
        int myInt1 = (int) MyFloat1;
        char myChar1 = (char) MyFloat1;
        short myShort1 = (short) MyFloat1;
        byte myByte1 = (byte) MyFloat1;
        long Mylong2 = 126000L;
        double myDouble2 = (double) Mylong2;
        float myFloat2 = (float) Mylong2;
        int myInt2 = (int) Mylong2;
        char myChar2 = (char) Mylong2;
        short myShort2 = (short) Mylong2;
        byte myByte2 = (byte) Mylong2;
        int MyInt3 = 2500;
        double myDouble3 = (double) MyInt3;
        float myFloat3 = (float) MyInt3;
        long myLong3 = (long) MyInt3;
        char myChar3 = (char) MyInt3;
        short myShort3 = (short) MyInt3;
        byte myByte3 = (byte) MyInt3;
        char MyChar4 = 5;
        double myDouble4 = (double) MyChar4;
        float myFloat4 = (float) MyChar4;
        long myLong4 = (long) MyChar4;
        int myInt4 = (int) MyChar4;
        short myShort4 = (short) MyChar4;
        byte myByte4 = (byte) MyChar4;
        short MyShort5 = 4;
        double myDouble5 = (double) MyShort5;
        float myFloat5 = (float) MyShort5;
        long myLong5 = (long) MyShort5;
        int myInt5 = (int) MyShort5;
        char myChar5 = (char) MyShort5;
        byte myByte5 = (byte) MyShort5;
        byte MyByte6 = 1;
        double myDouble6 = (double) MyByte6;
        float myFloat6 = (float) MyByte6;
        long myLong6 = (long) MyByte6;
        int myInt6 = (int) MyByte6;
        char myChar6 = (char) MyByte6;
        short myShort6 = (short) MyByte6;
        System.out.println(bit);
        System.out.println(keves);
        System.out.println(sok);
        System.out.println(okt);
        System.out.println(hex);
        System.out.println(hosszu);
        System.out.println(lebegos);
        System.out.println(dupla);
        System.out.println(lebegosexpo);
        System.out.println(duplaexpo);
        System.out.println("Double:" + MyDouble);
        System.out.println("Doubleból float-ba:" + myFloat);
        System.out.println("Doubleból long-ba:" + myLong);
        System.out.println("Doubleból int-be:" + myInt);
        System.out.println("Doubleból char-ba:" + myChar);
        System.out.println("Doubleból short-ba:" + myShort);
        System.out.println("Doubleból byte-be:" + myByte);
        System.out.println("Float:" + MyFloat1);
        System.out.println("Floatból double-ba:" + myDouble1);
        System.out.println("Floatból long-ba:" + myLong1);
        System.out.println("Floatból int-be:" + myInt1);
        System.out.println("Floatból char-ba:" + myChar1);
        System.out.println("Floatból short-ba:" + myShort1);
        System.out.println("Floatból double-be:" + myByte1);
        System.out.println("Doubleból float-ba:" + myFloat2);
        System.out.println("Long:" + Mylong2);
        System.out.println("Longból double-ba:" + myDouble2);
        System.out.println("Longból int-be:" + myInt2);
        System.out.println("Longból char-ba:" + myChar2);
        System.out.println("Longból short-ba:" + myShort2);
        System.out.println("Longból byte-be:" + myByte2);
        System.out.println("Int:" + MyInt3);
        System.out.println("Intből float-ba:" + myFloat3);
        System.out.println("Intből double-ba:" + myDouble3);
        System.out.println("Intből long-ba:" + myLong3);
        System.out.println("Intből char-ba:" + myChar3);
        System.out.println("Intből short-ba:" + myShort3);
        System.out.println("Intből byte-be:" + myByte3);
        System.out.println("Char" + MyChar4);
        System.out.println("Charból float-ba:" + myFloat4);
        System.out.println("Charból double-ba:" + myDouble4);
        System.out.println("Charból long-ba:" + myLong4);
        System.out.println("Charból int-be:" + myInt4);
        System.out.println("Charból short-ba:" + myShort4);
        System.out.println("Charból byte-be:" + myByte4);
        System.out.println("Short" + MyShort5);
        System.out.println("Shortból float-ba:" + myFloat5);
        System.out.println("Shortból double-ba:" + myDouble5);
        System.out.println("Shortból long-ba:" + myLong5);
        System.out.println("Shortból int-be:" + myInt5);
        System.out.println("Shortból char-ba:" + myChar5);
        System.out.println("Shortból byte-be:" + myByte5);
        System.out.println("Byte" + MyByte6);
        System.out.println("Byteből float-ba:" + myFloat6);
        System.out.println("Byteből double-ba:" + myDouble6);
        System.out.println("Byteből long-ba:" + myLong6);
        System.out.println("Byteből int-be:" + myInt6);
        System.out.println("Byteből char-ba:" + myChar6);
        System.out.println("Byteből short-ba:" + myShort6);
    }
}